CodeFusionPF/pacto

client/src/pages/api/items.js
Las imágenes se volvieron a pasar como url en el json de productos mockup
=> fix/items_images 

client/src/components/productoCard.js, client/src/pages/productos.js, client/src/pages/prueba.js, client/src/styles/ProductoCard.module.css, client/src/styles/Productos.module.css
Bocetos iniciales para que Edward vaya colocando la lógica.
=> Feat/product card y página productos (bocetos)

client/src/components/menu.js, client/src/components/navbar.js, client/src/components/searchbar.js, client/src/pages/cart.js, client/src/pages/categorias.js, client/src/pages/faqs.js, client/src/pages/nosotros.js, client/src/pages/ofertas.js, client/src/styles/Footer.module.css, client/src/styles/Home.module.css, client/src/styles/NavBar.module.css
Primera versión "En construcción"
Agregados todos los links al navbar y al menú mobile
Necesita fix de línea azul debajo de los links del navbar.
Corregida palabra "produtos" del searchbar
=> feat/paginas_del_navbar_y_menu - versión En Construcción

client/src/components/rewiews.js, client/src/pages/api/rewiew.js, client/src/pages/index.js, client/src/styles/Rewiews.module.css
=>  en proceso rewiews

client/src/styles/FilterPanel.module.css, client/src/styles/Paginado.module.css, client/src/styles/ProductoCard.module.css, client/src/styles/Productos.module.css, client/src/styles/SortComponent.module.css, client/src/styles/globals.css
- Ajusté estilos de la página productos y de todos sus componentes.
- Lo que todavía luce muy mal son los selects (para el ordenamiento y para las categorías). Eso porque para realizar los últimos ajustes, necesitaba modificar los archivos de los componentes (y Alex y Edward están trabajando sobre ellos). 
Pero dejé los estilos listos, cuando pueda tocar los archivos de los componentes hago los ajustes en un momento.
- Respecto al panel de filtrado, están los estilos para que sea responsive, pero resta programar la lógica de los botones que lo mostrarán/ocultarán en tamaño mobile (tampoco lo hice porque había que tocar los archivos de los componentes).
=> Refactor/productos page/estilos

backend/routes/products.js
Ajuste a la ruta de consulta de productos por nombre, se modifica para que no colicione con la ruta Get by Id, la ruta queda /productsname
=> Fix/Get Productos por nombre

client/src/components/filterPanel.js, client/src/components/sortComponent.js, client/src/styles/FilterPanel.module.css, client/src/styles/Productos.module.css, client/src/styles/SortComponent.module.css, package-lock.json
- Ajustados los estilos de los selects de las categorías y del selector de ordenamiento.
**Refactor necesario en algún momento:**
- Cuando se selecciona una sub-categoría, el valor luce igual que los nombres de las demás categorías (el usuario no tiene feedback visual adecuado sobre la/s categorías de las cuales seleccionó un valor).
- Intenté solucionarlo dando un estilo diferente a aquellos selects que tengan un valor seleccionado, pero los navegadores restringen mucho la customización de esos aspectos de los selects (hay que recurrir a trucos más elaborados con los cuales no tengo experiencia).
- Se me ocurren algunas ideas para el siguiente sprint, pero no para este (no creo que no diera el tiempo).
=> Refactor/productos page/select styles

backend/controllers/product/APIgetProductByFilters.js, backend/database/controllers/products/productGet/Handlers/handlerFilters.js, client/src/components/ProductList.js, client/src/components/paginado.js, client/src/components/productoCard.js, client/src/redux/features/products/productsSlice.js
Se arregló un bug el cual impedía que los productos se paginaran, tambien se arregló que el paginado refleje la cantidad de paginas segun los productos mostrados por pagina.
Por otro lado, se arregló un bug que no filtraba los estados de un producto  de manera combinada (Si traias solo los nuevos filtraba bien pero si filtrabas, por ejemplo, por nuevos Y reacondicioinado el back no traía ningún producto)
=> FIX: Fixed bug in the pagination

backend/controllers/user/APILoginUser.js, backend/database/mongoose.js
Creado el esqueleto del controlador para loggear a un user
=> ADDED Base for login controller

client/src/pages/productos/[id].js
Añadido slider para las imágenes en el detalle del producto.
=> refactor/productDetail:add_Carousel

client/src/pages/sellProduct.js, client/src/styles/sellProduct.module.css
- Ahora permite enviar varias imágenes
- Se agregaron previsualizaciones de las imágenes seleccionadas
- Se agregó lógica para que, luego de enviar la data del form, se limpie el formulario y redirija a la página de productos
**Refactor necesario a futuro:**
- Que redirija al detalle del producto recientemente creado (cuando el backend nos pueda devolver el nuevo producto con su ID)
**Refactor necesario si da el tiempo:**
- Agregar funcionalidad que permita eliminar una o todas las imágenes cargadas (si el usuario eligió la foto equivocada o si simplemente quiere cambiarla).
=> Refactor/sell product/images

client/src/api/categoriesApi.js, client/src/pages/sellProduct.js, client/src/redux/features/categories/categoriesSlice.js, client/src/redux/store.js
- Ahora los selects de Categorías y SubCategorías toman los datos de la BD
- Para esto, tuve que agregar una propiedad más al **Store de Redux** (categories)
=> Refactor/sell product/selects from backend

client/src/pages/sellProduct.js
Ajuste de los datos enviados desde el frontend.
🥳**Con esto quedó funcionando correctamente la creación de un nuevo producto.**🥳
Resta hacer un par de ajustes para que esté 100% lista esta parte:
1. Configurar Cloudinary para que redimensione las imágenes muy grandes al subirlas
2. Controlar el formulario
✅ Haré ambas cosas en el correr del día de hoy.
=> Refactor/sell product/data adjusts

client/src/api/productsApi.js, client/src/pages/sellProduct.js, client/src/redux/features/products/productsSlice.js, client/src/styles/sellProduct.module.css
**Ahora el formulario está controlado**
- Todos los campos tienen implementadas restricciones (en el objeto "validation" del componente sellProduct.js se pueden ver todas las que tiene cada campo).
- El control sobre la cantidad y tipo de los archivos subidos está parcialmente controlados: 
ante un archivo incorrecto o una cantidad superior a la permitida, aparece mensaje de error y no se permite el envío del formulario, pero lo ideal sería impedir que se adjunten esos archivos.
**Ahora luego de creado el producto, redirige a la página con el detalle del mismo**
**Extras**
- En las miniaturas de las imágenes aparece botón para eliminar el archivo adjuntado (AÚN NO FUNCIONA)
- Mientras se obtiene la respuesta del backend, se muestra un spinner en el botón de Publicar, para dar feedback al …
=> Feat/sell product/form controls

backend/controllers/user/APILoginUser.js, backend/controllers/user/APIpostNewUser.js
* Ahora el login (manual) comprueba que un usuario este verificado para poder ser loggeado o no.
* En caso de que no este verificado, se mandará el mail con el nuevo codigo de verificacion y retornara un json con dicha informacion para ser usada en el frontend y poder redirigir al usuario a la ventana de verificación.
* Cada vez que el usuario se loggee de manera manual, se le asignará un nuevo token por cuestiones de seguridad.
Los casos en que se asigna un nuevo token es cuando: 
- Un usuario se loggea de forma exitosa.
- Un usuario se loggea, existe en la base de datos PERO no está verificado.
=> Change in APILoginUser.js

client/package-lock.json, client/package.json, client/src/pages/firebase.js, client/src/pages/login.js, client/src/styles/Login.module.css
falta la ruta para conectar con el back :)
=> Implementacion de Firebase en el front

backend/controllers/product/APIgetProductByFilters.js
* Se corrigió un bug el cual impedia ver la cantidad correctas de productos si se aplicaban filtrados (Siempre se mostraba la cantidad total de productos en la DB, ahora muestra la cantidad de productos según filtros aplicados)
=> Fixed bug with amount of products if filters are applied

backend/firebase/firebaseAdmin.js, client/src/redux/features/auth/authSlice.js
edite el reducer para que ahora tenga el localstorage el usuario que se logea por google, tanto cuando se registra por primera vez, como cuando ya existe en la DB, tambien edite la ruta de firebaseAdmin para enviar el token y el user por google
=> fixed google token

backend/controllers/user/APIRecoveryPassword.js, backend/controllers/user/APIRecoverySendCode.js, backend/middlewares/checkUserMiddleWare.js, backend/routes/users.js
* Se agrego la ruta para restablecer una contraseña (La ruta recibe email, neuva password y el codigo de recuperación).
* A la ruta se le agregó un middleware que verifique que esten todos los datos antes de ceder el paso.
* Se agregó el controller que se encarga de estabelcer la nueva contraseña.
* La nueva contraseña se hashea de la misma forma que cuando se registra un usuario nuevo.
* Retorna los mensajes correspondientes según cada caso (Faltan datos, el codigo no coincide, el email ingresado no coincide con ninguno de la DB, caso de exito).
* Ya se puede conectar con el front
=> Added the route and controller to set the new password of an user

backend/database/mockData/infoColombia.json
* Se agregó un json a mockdata con la información de todos los departamentos, y sus correspondientes municipios, de Colombia
=> Added a json with information of all deparmetns and cities of Colombia

backend/database/mockData/infoColombia.json, backend/database/mockData/testData.js, backend/database/models/city.js, backend/database/models/department.js, backend/database/mongoose.js, backend/database/schemas/citySchema.js, backend/database/schemas/departmentSchema.js
* Se creo el esquema y modelo para ciudades y departamentos de colombia.
* Se creo la funcion para pasar la data del mock (json con todos los deptos y ciudades) a la base de datos.
* No descomentar el load() porque van a estar un buen rato esperando a que se carguen todas las ciudades jajaja
=> Schemas, models and upload of departments and cities is working now

backend/controllers/user/APIEditUser.js, client/src/pages/profileUser.js, client/src/redux/features/auth/authSlice.js, client/src/styles/profileUser.module.css
Edicion de datos de usuario funcional 👍
=> Edit user connect front con back

backend/database/controllers/transactions/DBPurchasedProducts.js, backend/database/controllers/transactions/DBSetBalance.js, backend/database/controllers/transactions/DBStateGetOrder.js, backend/database/controllers/transactions/DBStateSetOrderByClient.js, backend/database/controllers/users/userPost/DBUserCreate.js, backend/database/models/order.js, backend/database/models/wallet.js, backend/database/schemas/orderSchema.js, backend/database/schemas/userSchema.js, backend/database/schemas/walletSchema.js
1) se agregaron las wallet de usuarios donde se registran:
-pendingBalance: monto que esta pendiente hasta que se entregue el producto al comprador
-receivableBalance: monto disponible para cobrar (se establece cuando el producto se entrega al comprador y se descuenta de pending)
2) se reformularon las ordenes para tener mejor y facil acceso desde el panel de admin
=> Wallet updated

backend/controllers/product/APIpostNewProduct.js, backend/database/controllers/products/productGet/DBProductGetId.js, client/src/pages/productos/[id].js, client/src/pages/sellProduct.js, client/src/redux/features/products/productsSlice.js
-fixie ver detalles de productos
-fixie postear productos
(FALTA IMPLEMENTAR TOKEN PARA ARREGLAR BUG)
=> Fixed Detail

client/src/pages/sellProduct.js
Fixeado vender productos 👍, funcional correctamente
=> Fixed vender producto

backend/controllers/user/APIgetAllUsers.js, backend/database/controllers/users/userGet/DBAllUsers.js, backend/database/helper/DBcheckUserExists.js
* Se agregó el nombre del departamento y ciudad entre la data retornada de un usuario.
Esta data tendra la siguiente estructura en la key "city":
city: {
_id: new ObjectId("646261f19a743f205356ea84"),
codeDane: '5.001',
city: 'Medellín',
department: { department: 'Antioquia' },
       __v: 0
 }
 
* Se agregó el total  de usuarios en la DB como respuesta cuando se usa la ruta de admin /users.
 
* Se restructuró el archivo checkUserExists ya que repetia demasiado codigo. Tal vez deba crearse un nuevo archivo para delegar responsabilidades.
=> Added city and department names to the user info returned

backend/controllers/user/APIgetSellerById.js, backend/database/helper/DBCheckProductExists.js, backend/routes/users.js
* Se agrego la ruta /seller, esta ruta recibe por query el id de un producto y retorna la data del usuario (vendedor) referido a ese prod.
* Se creo el controller que se comunica con la ruta.
=> Added route and controller to get data of a seller

client/src/pages/profileUser.js, client/src/styles/profileUser.module.css
depasrtment y city implementado en perfil de user y en edituser funcional completo
=> depa y city en user y edituser implementada

backend/app.js, backend/controllers/question/APIPostNewQuestion.js, backend/routes/questions.js
* Se agregó la ruta /question de tipo post para publicar una pregunta para un producto.
* El controller que llama la ruta recibe un idProduct, idUser y la question.
=> Added route and controller to post a new question

client/src/components/ModalReview.js, client/src/pages/prueba.js
Falta ajustar según cambios del esquema de las reviews de la BD.
Luego de mergear, termino los ajustes necesarios y subo PR con la versión final.
=> feat/calificaciones/ingresar: primera versión lista

backend/app.js, backend/controllers/reviews/APIGetVendorReviews.js, backend/controllers/reviews/APIPostNewReview.js, backend/controllers/user/APIgetAllUsers.js, backend/database/controllers/reviews/reviewPost/DBReviewPost.js, backend/database/controllers/sales/DBGetSaleById.js, backend/database/mongoose.js, backend/routes/reviews.js
* Se agregó la ruta post /review, esta ruta recibe por body el idUser, review (otro objeto que contendrá calification y la review en si) y el idVendor.
* La ruta /users retorna la fecha de registro 
* Se cambio la estructura de la review que se envia al controlador de la DB
* Se agregó la ruta get /vendorReviews, esta ruta recibe por query el id de un vendedor  y el numero de pagina que desea obtener. Retorna la cantidad total de reviews que tiene ese vendedor y tambien 10 reviews a ese vendedor y correspondiente a la pagina solicitada
=> Added route and controller to post new review

backend/controllers/reviews/APIGetAllReviews.js, backend/database/controllers/reviews/reviewGet/DBGetAllReviews.js, backend/routes/reviews.js
* Se agregó la ruta get /reviews, recibe por query el numero de pagina y retorna las todas reviews acorde a la pagina solicitada (ordenadas por fecha) y el total de reviews que hay en la DB.
* Se creó el controlador de la DB encargado de traer todas las reviews de la DB al back.
* Se creó el controlador de la API encargado de manipular las reviews traidas por el controlador de la DB y mandarselas al front.
=> Added route, api controller and db controller to get all reviews in DB

backend/controllers/product/APIAdminGetAllProds.js, backend/database/controllers/products/productGet/Handlers/handlerGetAll.js, backend/routes/products.js
* Se agregó ruta de administrador para traer todas los productos en la base de datos (independientemente del estado).
* La ruta retorna los productos según la pagina enviada por query y tambien la cantidad total de productos en la db.
Estructura:
{
totalProducts: 54,
products: [prod1, prod2, prod3]
}
=> Added ADMIN route and controller to get all products from DB

client/src/components/ModalReview.js, client/src/pages/prueba.js
Desde el componente ModalReviews se registran las reviews correctamente!🥳
Falta conectar con el resto de los componentes para cerrar el ciclo de compra/calificación.
=> ModalReviews conectado con el back. Se registra Review OK

client/src/components/filterPanel.js, client/src/pages/profileUser.js, client/src/styles/FilterPanel.module.css
-Userperfil por google fixeado
-filter modificado
=> fixed price and userpage

backend/controllers/question/APIGetQuestions.js, backend/controllers/question/APIPostNewAnswer.js, backend/database/controllers/questions/questionGet/DBGetQuestions.js, backend/database/mongoose.js, backend/routes/questions.js
* Se creo la ruta post /answer para postear una respuesta para una determinada pregunta. Recibe por body el idUser, un objeto con la estructura de una respuesta y el idQuestion
* Se creo la ruta get /questions para traer todas las preguntas y respuestas de un determinado producto. Esta ruta recibe por query el id del producto determinado
=> Added routes and controllers to post and get questions and answers

client/src/components/menu.js, client/src/components/navbar.js, client/src/components/searchbar.js, client/src/pages/login.js, client/src/styles/NavBar.module.css
- ahora en Searchbar buscasun producto y si no estas en products te direcciona ahi
- en loginpage cambie el encabezado de PACTO por H2H
- Ahora si eres admin te sale la opcion de admin panel tanto en el navbar como en el menu lateral
=> ultimos arreglos

client/src/components/cart/productCart.js, client/src/components/transactions/Orders.js, client/src/pages/cart/detailCart.js, client/src/pages/cart/shipmentCart.js, client/src/pages/orders/index.js, client/src/pages/profileUser.js, client/src/redux/features/auth/authSlice.js
update user data, show real data on shopping Cart(totalprice, amount), show real date  of creation of orders
=> fixed bugs

client/src/api/productsApi.js, client/src/api/usersApi.js, client/src/components/dashboard/admin/BarChart.js, client/src/components/dashboard/admin/BarChartWallets.js, client/src/components/dashboard/admin/OrdersList.js, client/src/components/dashboard/admin/ProductsList.js, client/src/components/dashboard/admin/WalletsList.js, client/src/components/enConstruccion.js, client/src/pages/dashboard/admin/calificaciones.js, client/src/pages/dashboard/admin/configuracion.js, client/src/pages/dashboard/admin/preguntas.js, client/src/pages/dashboard/admin/productos/[id].js, client/src/pages/dashboard/admin/usuarios/[id].js, client/src/pages/dashboard/admin/ventas/[id].js, client/src/styles/EnConstruccion.module.css
Ajustes finales del panel Admin
=> Admin dash/ajustes varios
